### ISSUE TITLE
High CPU usage when web server is idle

### ISSUE THREAD

**Issue by ebartek** [embedthis/goahead#112]
<h3>Environment</h3>
GoAhead Version: 3.4.1, built from source
O/S: Linux Debian 4.0
Hardware: PC
Customization: Using own custom security handler and urls route handler. Not involved in this issue.
Configure command line:
<pre><code>./configure --with openssl</code></pre>
<h3>Problem Description:</h3>
When Linux starts Webs and Webs just listening at:
<pre><code>https://localhost/</code></pre>
CPU usage is too high. Top command returned: 
 
![cpu_usage](https://cloud.githubusercontent.com/assets/562955/5440759/6828cfc2-848b-11e4-8094-b017e054926e.png)

But I expected that when the web server is idle it does not take much CPU time. 
<h3>Http Headers</h3>
No http requests and responses. Web server just listening and waiting for requests. As you can see on the picture sy (system cpu time or % CPU time spent in kernel space) is also big.
<h3>GDB Backtrace</h3>
<pre><code>#0  0xb7574cd7 in select () from /lib/tls/libc.so.6
#1  0xb7989ad9 in socketSelect (sid=3, timeout=0) at socket.c:568
#2  0xb797d103 in websServiceEvents (finished=0xb799ab3c) at http.c:1317
#3  0xb7978a0f in MAIN(goahead, int argc, char **argv, char **envp) goahead.c:43</code></pre>

When I changed timeout passed to socketSelect method to value greater than 0 [ms] CPU usage is back to normal.

**Comment by ebartek** [comment]
Hi,
I am very glad that you were able to reproduce a similar issue. It looks so far that the proto-fix works perfectly for us. 
When are you going to release an official patch with the fix ?
Thanks for your help.

**Comment by embedthis** [comment]
Targeted for the end of this month. May be released as 3.5 if some of the changes impact compatibility in any way. We're adding support for the Expansive web site manager to bring templates, layouts, partials and build support to GoAhead. Currently this is all external to GoAhead and is not impacting compatibility.

**Comment by embedthis** [comment]
Release has been delayed till end Feb.
