### ISSUE TITLE
Run-time password changing / user adding / user deleting

### ISSUE THREAD

**Issue by bigskang** [embedthis/goahead#113]
GoAhead does not seem to support run-time password changing.

The function umSetUserPassword that is 2.x API is removed at 3.x. So I have implemented the changing password function with two 3.X APIs; websRemoveUser and websAddUser.

I was faced with the following problem after I have implemented it.
When the user is newly authorized on the new browser, user have to use the new changed password. It's what I want.
But, if there is a old session(?) that have been already authorized using old password on a browser, the old browser don't need to be authorized again and the old browser have no limit on navigating.

Could you please show the how I can make the old sessions to be invalid when user is removed or user's password is changed?
Or, do you have a plan to support run-time password changing after?

I am using web form based authentication.

**Comment by peterhale** [comment]
You could try this code:

```
PUBLIC int websSetUserPassword(char *username, char *password)
{
    WebsUser    *user;

    assert(username && *username);
    if ((user = websLookupUser(username)) == 0) {
        return -1;
    }
    wfree(user->password);
    user->password = sclone(password);
    return 0;
}
```
GoAhead uses a cookie and session to track logged in users. The logout routine is currently not declared as a public API. You could try this routine.

```
PUBLIC int websLogoutUser(Webs *wp)
{
    assert(wp);
    websRemoveSessionVar(wp, WEBS_SESSION_USERNAME);
    if (smatch(wp->authType, "basic") || smatch(wp->authType, "digest")) {
        websError(wp, HTTP_CODE_UNAUTHORIZED, "Logged out.");
        return;
    }
    websRedirectByStatus(wp, HTTP_CODE_OK);
}
````
We'll test and add both APIs in the next release.

**Comment by bigskang** [comment]
Thanks for your quick response and support.

The new two APIs work well, except one case.
There were two browsers received certificate using same userID and same password from a GoAhead server at the moment. At this time, password of the user was changed from one of the two browsers. The browser that did password changing will be logouted through new API but the other one can still navigate without no limit.

Could you write a API that makes all sessions using same userID to be logouted?

Many thanks.

**Comment by bigskang** [comment]
I have written the function that I want and it seems to work.
Please review this code. Can it make any problem or memory leak? Please finalize it, if there are mistakes.

PUBLIC void websRemoveUserSession(char *username)
{
    WebsSession     *sp;
    WebsKey         *sym, *next;

    assert(username);

    for (sym = hashFirst(sessions); sym; sym = next) {
        next = hashNext(sessions, sym);
        sp = (WebsSession*) sym->content.value.symbol;

        WebsKey         *var_sym;
        if( (var_sym = hashLookup(sp->cache, WEBS_SESSION_USERNAME)) == 0 )
            continue;

        if( smatch(username, var_sym->content.value.symbol) )
        {
            hashDelete(sessions, sp->id);
            sessionCount--;
            freeSession(sp);
        }
    }
}

**Comment by embedthis** [comment]
I'm not convinced that is the right approach or universally applicable. May need to be custom code for you.

When a password is changed, that does not invalidate previously authenticated users. Their authentication is still valid. It is just the password for next time use is different.
