### ISSUE TITLE
Https Only Webserver (version 2.1.5)

### ISSUE THREAD

**Issue by yvk2493** [embedthis/goahead#114]
How can i set Goahead webserver to serve only Https requests. or how can i redirect all the traffic to https.
I am using Version : 2.1.5
Currently it accepts only http requests on port 80. Are there any changes needed in source code ??
Please mention the procedure to serve only https requests.

Thanks,
yvk

**Comment by peterhale** [comment]
GoAhead 3, you change the listen property in main.me and reconfigure. This defines the ME_GOAHEAD_LISTEN definition.

            listen: ['https://*:443']

GoAhead 2.1.5 is ancient ... you will need to locate the code that sets up the listen.

**Comment by yvk2493** [comment]
Thanks peterhale :)
Does anyone who uses this version have any idea how to enable https ?
I Can't find this listen configuration in this version. 
@admin
Does version 2.1.5 support https ?

**Comment by yvk2493** [comment]
Some More Info :
I enabled the Related Macros of SSL. (OPENSSL & WEBS_SSL_SUPPORT)
When I tried to capture the traffic from Wireshark tool. 
I am not seeing any Server hello packet in response to Client hello Packet sent by Browser. so I am guessing either My SSL library is not loaded or SSL is not up.
I checked the Linkage of Library by LDD command and it is properly linked. But I don't know how can i check Whether SSL is up or not (Like in Apache "SSLengine on" command). Is der any command for goahead too ?
or is there any other method to check SSL status ??

I am Cross compiling this Binary to QNX Os. Details (QNX localhost 6.3.2 2006/03/16-14:19:50EST x86pc x86)

**Comment by yvk2493** [comment]
Finally got some results.
Enabled the Logs to see where it is failing and on fixing that Now I am able to connect to Node through HTTPS connection.
And for Connecting only HTTPS I just Closed the HTTP connection after it was set up so Now it only accepts HTTPS connections.
But Still I am facing one problem :(
I am not able to Download Jar files through this Https Connection .When I tried to capture the packets by wireshark I am seeing a TCP/IP Offload Error. More Specifically the Error is 
" Header checksum: 0x0000 [incorrect, should be 0x2c0e (maybe caused by "IP checksum offload"?)] " 
in each of the packets from My computer to Node where Web server is hosted.

I am guessing may be because of this error i am not able to download Files. Or is there any option to enable/Disable File download in Web Server it self ?
Did anyone face this issue ?
 Please Help
