### ISSUE TITLE
How do I configure digest authentication?

### ISSUE THREAD

**Issue by ebartek** [embedthis/goahead#115]
<h3>Environment</h3>
GoAhead Version: 3.4.3, built from source
O/S: Linux Debian 4.0
Hardware: PC
Customization: No modification to the code, only configuration of auth.txt and route.txt.
Configure command line:
<pre><code>./configure --with openssl</code></pre>
<h3>Problem Description:</h3>
When I try to open the website 
<pre>https://mysite/admin.asp<code></code></pre>
Web server is asking for user name and password (login dialog box is displayed). Our website/web server requires digest authentication.
I do not type any user name and password, I leave the fields empty, then I click OK then requested web page is displayed. The following data is sent and returned
<pre><code>URL          Status
GET admin.asp          200 OK

Request:
Cache-Control	no-cache
Connection	close
Content-Type	text/html
Date	Thu Feb 19 17:03:30 2015
Pragma	no-cache
Server	GoAhead-http
Transfer-Encoding	Chunked

Response:
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding	gzip, deflate
Accept-Language	en-US,en;q=0.5
Authorization	Digest username="", realm="MyRealm", nonce="NzI1YmYyOTViN2RhZjdhMTY3MjA2MTYyYTQ4NTMzMTA6V2ViRGlhZ25vc3RpY3M6NTRlNjE3NTc6MA==", uri="/admin.asp", algorithm=MD5, response="9b8e16b295d8d88328c7734f70393ad0", opaque="5ccc069c403ebaf9f0171e9517f40e41", qop=auth, nc=00000001, cnonce="84522e2e8d66bc5c"
Connection	keep-alive
Cookie	loggedOn=NO
Host	10.76.37.126:8443
User-Agent	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</code></code></pre>

But I expect that the web server will return a response with status 401 “Access Error: Unauthorized/Access Denied: User not logged in.”  when no user and no password are typed in the login dialog box. 

If I type invalid user name or invalid password then "Access denied: invalid user name or User not logged in" is returned by the web server. Status of the web response is 401 Unauthorized.
<h3>URI routes</h3>
<pre><code>route uri=/admin auth=digest</code></pre>

**Comment by embedthis** [comment]
Can you post the exact auth.txt and route.txt you are using?

That scenario is part of our test suite and works fine here.

**Comment by ebartek** [comment]
<h3>auth.txt</h3>
I have one user, not used in my test case.
<pre><code>user name=joshua password=2fd6e47ff9bb70c0465fd2f5c8e5305e roles=manager,purchaser</code></pre>
<h3>route.txt</h3>
I have just one route configured:
<pre><code>route uri=/admin auth=digest</code></pre>

<h3>Trace log</h3>
Trace level set to 9 (verbose). Some private information were deleted:
<pre><code>
Webs: 4: New connection from source_ip:47022 to destination_ip:8080

&lt;&lt;&lt; Request
GET /admin.asp HTTP/1.1
Accept: application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*
Accept-Language: en-US,zh-CN;q=0.5
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
Accept-Encoding: gzip, deflate
Host: destination_ip:8080
Connection: Keep-Alive
Cache-Control: no-cache
Webs: 5: Examine route /admin
Webs: 2: Access Denied. User not logged in.

&gt;&gt;&gt; Response
HTTP/1.1 401 Unauthorized
Server: GoAhead-http
Date: Mon Feb 23 10:08:31 2015
WWW-Authenticate: Digest realm="MyRealm", domain="destination_ip:8080", qop="auth", nonce="ZTBmM2QwMDU0N2NhNmJkY2RhNzBmMDFiNjI2YmNkNmE6V2ViRGlhZ25vc3RpY3M6NTRlYWZjMWY6MA==", opaque="5ccc069c403ebaf9f0171e9517f40e41", algorithm="MD5", stale="FALSE"
Content-Length: 202
Connection: close
Content-Type: text/html
Webs: 6: websFlush: buflen 603
Webs: 6: websFlush: wrote 603 to socket
Webs: 5: Close connection

<p><b>So far it is ok. Web Browser asks for user name and password. I just click OK.</b></p>
&lt;&lt;&lt; Request
GET /admin.asp HTTP/1.1
Accept: application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*
Accept-Language: en-US,zh-CN;q=0.5
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
Accept-Encoding: gzip, deflate
Host: destination_ip:8080
Connection: Keep-Alive
Cache-Control: no-cache
Authorization: Digest username="",realm="MyRealm",nonce="ZTBmM2QwMDU0N2NhNmJkY2RhNzBmMDFiNjI2YmNkNmE6V2ViRGlhZ25vc3RpY3M6NTRlYWZjMWY6MA==",uri="/admin.asp",cnonce="7b46d446ae3ac50cad9e1a62b36afec8",nc=00000001,algorithm=MD5,response="2d9ad85ed25d20641d5edf0bdda544dc",qop="auth",opaque="5ccc069c403ebaf9f0171e9517f40e41"
Webs: 5: Examine route /admin
Webs: 2: Access denied: user is unknown
Webs: 5: Route /admin calls handler file

<p><b>Webs returned access denied: user is unknown but the route/handler is processing the request :(</b></p>
&gt;&gt;&gt; Response
HTTP/1.1 200 OK
Server: GoAhead-http
Date: Mon Feb 23 10:08:34 2015
Content-Length: 484
Connection: close
Content-Type: text/html
Last-Modified: Mon Feb 23 10:07:56 2015
Webs: 6: websFlush: buflen 179
Webs: 6: websFlush: wrote 179 to socket
Webs: 6: websFlush: buflen 0
Webs: 5: Close connection

<p><b>Admin.asp requires and loads common.js. Next request/response is only to show that admin.asp was returned by Webs. Suitable route is not set but it is OK for the test purpose.</b></p>
&lt;&lt;&lt; Request
GET /scripts/common.js HTTP/1.1
Accept: */*
Referer: http://destination_ip:8080/admin.asp
Accept-Language: en-US,zh-CN;q=0.5
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
Accept-Encoding: gzip, deflate
Host: destination_ip:8080
Connection: Keep-Alive
Cache-Control: no-cache
Authorization: Digest username="",realm="MyRealm",nonce="ZTBmM2QwMDU0N2NhNmJkY2RhNzBmMDFiNjI2YmNkNmE6V2ViRGlhZ25vc3RpY3M6NTRlYWZjMWY6MA==",uri="/scripts/common.js",cnonce="7b46d446ae3ac50cad9e1a62b36afec8",nc=00000002,algorithm=MD5,response="366ca65b6e7d84912d95c6e44798c098",qop="auth",opaque="5ccc069c403ebaf9f0171e9517f40e41"
Webs: 5: Examine route /admin
Webs: 2: Cannot find suitable route for request.

&gt;&gt;&gt; Response
HTTP/1.1 404 Not Found
Server: GoAhead-http
Date: Mon Feb 23 10:08:34 2015
Content-Length: 201
Connection: close
Content-Type: application/x-javascript
Webs: 6: websFlush: buflen 361
Webs: 6: websFlush: wrote 361 to socket
Webs: 5: Close connection
</code></pre>

**Comment by embedthis** [comment]
We can reproduce this. Thank you for capturing the issue.

The issue is caused by not calling route->askLogin when parsing the auth details fails. We'll prepare a fix this week and commit to the dev branch. You should be able to extract a patch from there ... or you can test the 3.4.4 code base.

Thanks
