### ISSUE TITLE
Does Goforms (Actions in New Versions) support Https ?

### ISSUE THREAD

**Issue by yvk2493** [embedthis/goahead#117]
Does Goform work with https ?? 
If it supports is there any extra processing/Notation needed tto specify in URL ?

Problem : 
I am able to Process a function using GoForm on HTTP but the same function is not responding on HTTPS.
http://10.220.xx.yy/goform/DoSomeThing?codebase=http://10.220.xx.yy/&amp;name=github&amp;value=Top

This works but Https one doesn't do any action.
https://10.220.xx.yy/goform/DoSomeThing?codebase=https://10.220.xx.yy/&amp;name=github&amp;value=Top
Any Help is Appreciated !!!

**Comment by embedthis** [comment]
Yes, there is nothing special about goforms for HTTPS.

Does general https work for html pages?

The goahead --log filename:4

should give you more trace. Always post the HTTP headers from this log in questions.
