### ISSUE TITLE
Compile error: Closing curly bracket with no opening bracket

### ISSUE THREAD

**Issue by koffienoot** [embedthis/goahead#123]
# Environment
GoAhead Version: 3.4.4, built from source, embedded in CPP application
Hardware: PC

# Problem Description
When compiling a .cpp file that includes _goahead.h_, compilation fails on a closing curly bracket that has no opening counterpart @ **goahead.h:3583**. Including _goahead.h_ inside an `extern "C"` block will fail as well, unless the block is not closed. This provides for an ugly workaround.

**Comment by embedthis** [comment]
Thanks for reporting. Just had this independently reported too.

goahead.h is missing an extern "C" {, declaration. Here is a quick patch.

```
diff --git a/src/goahead.h b/src/goahead.h
index f7e31c2..c7a44c6 100644
--- a/src/goahead.h
+++ b/src/goahead.h
@@ -20,6 +20,10 @@

 /************************************ Defaults ********************************/

+#ifdef __cplusplus
+extern "C" {
+#endif
```
