### ISSUE TITLE
c++ compile error: type conflict on string type

### ISSUE THREAD

**Issue by koffienoot** [embedthis/goahead#124]
# Environment
GoAhead Version: 3.4.4, built from source, embedded in CPP application
Hardware: PC

# Problem Description
The enum value with the name 'string' of type WebsType conflicts with the standard c++ type string.
Propose to add a prefix to the value names of the enumerator, to prevent any possible type conflicts.

**Comment by embedthis** [comment]
"string" is not a reserved word in C++. 

Can you please provide some extra details.

* Your compiler
* Your O/S
* The actual output emitted by the compiler to flag the error

**Comment by koffienoot** [comment]
True. A refreshed look and some further investigation shows that the conflicting code should have explicitly specified the use of std namespace.

So this is not a bug it could be an enhancement, for it is not uncommon to refer to 'std::string' with just 'string'.

**Comment by embedthis** [comment]
True, but it would break compatibility. 

Thanks for confirming and reporting back.
