### ISSUE TITLE
Ports scan causes a program crash

### ISSUE THREAD

**Issue by ebartek** [embedthis/goahead#126]
<h3>Environment</h3>
GoAhead Version: 3.4.4, built from source
O/S: Linux Debian 4.0
Hardware: PC
Customization: No modification to the code.

<h3>Problem Description</h3>
Ports scan using nmap knocked out the web server. 
NMap command:
<pre><code>nmap -sV -v IP</code></pre>
Trace log:
<pre><code>Webs: 2: GET / HTTP/1.0
Webs: 2: OPTIONS / HTTP/1.0
Webs: 2: OPTIONS / RTSP/1.0
Webs: 2: Unsupported HTTP protocol
Webs: 2: GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0
Webs: 2: OPTIONS sip:nm SIP/2.0
Segmentation fault (core dumped)
</code></pre>

Details  of the last request:
<pre><code><<< Request
OPTIONS sip:nm SIP/2.0
Via: SIP/2.0/TCP nm;branch=foo
From: <sip:nm@nm>;tag=root
To: <sip:nm2@nm2>
Call-ID: 50000
CSeq: 42 OPTIONS
Max-Forwards: 70
Content-Length: 0
Contact: <sip:nm@nm>
Accept: application/sdp
Segmentation fault (core dumped)
</code></pre>

The issue does not occur on 3.4.1.

**Comment by embedthis** [comment]
We get:

```
HTTP/1.1 406 Not Acceptable
Server: GoAhead-http
Date: Tue May  5 16:25:42 2015
Content-Length: 20
Connection: close
goahead: 4: New connection from 127.0.0.1:58485 to 127.0.0.1:8080
```

Can you post your route.txt?

**Comment by ebartek** [comment]
Sorry, I can not post route.txt today.
Can you post some details of your request?

It is important to enable service and version detection: 

nmap -sV -v IP

**Comment by embedthis** [comment]
We can reproduce now and are testing a fix. 

See: https://github.com/embedthis/goahead/commit/4d95910ef73641e48f3f06de64a2a58c2e4bb7f6
