### ISSUE TITLE
Hardcoded username assertion failure

### ISSUE THREAD

**Issue by koffienoot** [embedthis/goahead#131]
# Environment
GoAhead embedded in cpp application.
PC, W7 x64

# Problem Description

When running the application, the following error is printed to the console:
>goahead: 0: Assertion username, failed at ../../WebServer/core/goahead/auth.c 992

Searching through the files, the only call to the function firing the assertion is: `wp->digest = calcDigest(wp, 0, wp->user->password);` in `auth.c:942`, so the assertion will always be triggered.

**Comment by embedthis** [comment]
Please see:  https://github.com/embedthis/goahead/issues/111

**Comment by koffienoot** [comment]
I don't know what extra information you require. The code path is quite clear.

**Comment by koffienoot** [comment]
Also not that on line 999 in auth.c, the following check is done: `if (username == 0) {`
This also shows that the assertion on line 992 is invalid.
