### ISSUE TITLE
Cannot bind to socket when IP address is not given

### ISSUE THREAD

**Issue by koffienoot** [embedthis/goahead#132]
# Environment
VxWorks 6.9

# Problem description
In the Windows / Unix-like version of `socketInfo`, the `ip` parameter is checked for `NULL` value, making it possible to just bind to a port for any address (from `socketListen` function), but the other version does not check for NULL value and immediately performs a string comparison on the `ip` parameter (which can be `NULL`). This causes the web server to not properly start up when not specifying an IP address under VxWorks.

**Comment by embedthis** [comment]
Please see: https://github.com/embedthis/goahead/issues/111

**Comment by koffienoot** [comment]
It's about the difference in implementation (and behaviour) between Windows and VxWorks for the particular function. It works in Windows without specifying an IP address but now in VxWorks, because, contrary to the Windows implementation, in the VxWorks implementation no null-pointer check is done.
