### ISSUE TITLE
Crash using digest authentication

### ISSUE THREAD

**Issue by wigior** [embedthis/goahead#133]
### Environment
GoAhead version: 3.4.4, built from source
OS: Ubuntu 14.04 x86-64
Hardware: PC
Customization: None

Build using:
```
make
```

Run with test/web as document root.

### Problem Description
When sending the following request, the server crashes:
```
GET /auth/digest/digest.html HTTP/1.1
Host: localhost
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Authorization: Digest username="joshua", realm="example.com", nonce="YWFwIG5vb3QgbWllcw==", uri="/auth/digest/digest.html", algorithm=MD5, response="4d33cab072708d58dac61f087c2515a5", opaque="5ccc069c403ebaf9f0171e9517f40e41", qop=auth, nc=00000001, cnonce="96ea32d950b36a0d"

```

This is a valid request, except for a changed Authorization nonce.

### Analysis
When a nonce is supplied that does not contain a colon, the server crashes on a null-pointer access in auth.c, line 978. The parseDigestNonce function parses the user-supplied authorization nonce without doing any input validation.

**Comment by embedthis** [comment]
Quick patch:

```
diff --git a/src/runtime.c b/src/runtime.c
index 849a42c..311c295 100644
--- a/src/runtime.c
+++ b/src/runtime.c
@@ -2332,6 +2332,9 @@ uint hextoi(char *hexstring)
     char      *h;
     uint        c, v;

+    if (!hexstring) {
+        return 0;
+    }
     v = 0;
     h = hexstring;
     if (*h == '0' && (*(h+1) == 'x' || *(h+1) == 'X')) {
```

**Comment by embedthis** [comment]
Thanks. Good issue report. The headers really help to give the complete context.
