### ISSUE TITLE
clientFilename in WebsUpload structure is not being saved

### ISSUE THREAD

**Issue by jjwebber** [embedthis/goahead#140]
When performing a file upload (GoAhead v3.4.4) the processUploadHeader function does not populate the clientFilename member of the WebsUpload structure correctly. 

When the following code was added, the processing of the "filename" key was broken. 

                value = websNormalizeUriPath(value);
                if (*value == '.' || !websValidUriChars(value) || strpbrk(value, "\\/:*?<>|~\"'%`^\n\r\t\f")) {
                    websError(wp, HTTP_CODE_INTERNAL_SERVER_ERROR, "Bad upload client filename");
                    return -1;
                }

It appears that the websNormalizeUriPath function requires a leading "/" in the filename. When uploading a file, the name does not include a leading "/".

**Comment by embedthis** [comment]
websNormalizeUriPath tests for the first character being "/". 

However, this routine is called by websValidateUriPath for validating request URIs and it does the same thing. The only other use of this in GoAhead standard, is for file upload.

Here is a patch. It removes the redundant test in websNormalizeUriPath.

```
diff --git a/src/http.c b/src/http.c
index 3273f0e..870cc29 100644
--- a/src/http.c
+++ b/src/http.c
@@ -3360,9 +3360,11 @@ PUBLIC char *websNormalizeUriPath(char *pathArg)
     }
     wfree(dupPath);
     wfree(segments);
+#if UNUSED
     if ((path[0] != '/') || strchr(path, '\\')) {
         return 0;
     }
+#endif
     return path;
 }
```
