### ISSUE TITLE
please help with dvr

### ISSUE THREAD

**Issue by Leorot** [embedthis/goahead#151]
Hello,

I am not sure that I post in the right place. I have a no brand DVR and it has a goahead web server implemented. With windows 8.1 I was able to access my dvr using a router, from my pc. Since I upgraded to Windows 10 I am no longer able to remotely access my dvr. 

Is there any codec or piece of software able to help me out ? Thank you.

**Comment by embedthis** [comment]
You need to contact your DVR manufacturer. They customize the software.
