### ISSUE TITLE
Error prone assert() definition in non-debug version.

### ISSUE THREAD

**Issue by przem312** [embedthis/goahead#161]
The assert() definition when ME_GOAHEAD_DEBUG define is not set looks like this:
    #define assert(C)       if (1) ; else
If someone forgets about semicolon after using assert(), the code will compile and next line of code after assertion statement will be included in the else statement. I recommend putting brackets to else statement or changing the definition to (void)C

**Comment by embedthis** [comment]
Testing:

```
#define assert(C)       if (1) ; else ((void*)0)
```

**Comment by przem312** [comment]
When C is a function, it will be not executed. Consider this:
http://goo.gl/eHWRqK

**Comment by embedthis** [comment]
I think we have a different definition of assert.

When release mode, we do NOT want it to invoke the function. It MUST be compiled out and have zero cost to the program.

**Comment by przem312** [comment]
Agree on that. Please ignore previous comment.

**Comment by embedthis** [comment]
Problem with this solution.

Vxworks emits:

:180:5: warning: statement with no effect [-Wunused-value]

**Comment by embedthis** [comment]
Changed to else {}
