### ISSUE TITLE
Error prone wfree() definition

### ISSUE THREAD

**Issue by przem312** [embedthis/goahead#162]
The wfree() definition when ME_GOAHEAD_REPLACE_MALLOC define is not set looks like this:
wfree(p) if (p) { free(p); } else
If someone forgets about semicolon after using wfree(), the code will compile and next line of code after freeing will be included in the else statement. I recommend putting brackets to else statement.

**Comment by embedthis** [comment]
Testing:

```
 #define wfree(p) if (p) { free(p); } else ((void*)0)
```

**Comment by przem312** [comment]
calling free on null pointer is guaranteed to be safe

**Comment by embedthis** [comment]
Unfortunately not on all embedded systems.

**Comment by embedthis** [comment]
Changed to {} instead of ((void*)0)
