### ISSUE TITLE
WebsTime assumes signed definition of time_t

### ISSUE THREAD

**Issue by przem312** [embedthis/goahead#165]
<h3>Environment</h3>

<p>GoAhead Version: 3.4.6<br>
O/S: VxWorks 5.9<br>

<h3>Problem Description:</h3>

<p>Http header field "if-modified-since" is parsed to WebsTime(aka time_t) value.</p>
<p> Some error checks are assuming, that value of processed WebsTime can be lower than 0.</p>
<p>The VxWorks 5.9 translation of time_t type is size_t, therefore date parsing does not work at all</p>
<p>Consider this:</p>
<pre><code>
static WebsTime dateParse(WebsTime tip, char *cmd)
{
 WebsTime    parsedValue, dateValue;
int         index, tmpIndex, weekday, timeValue;
 (...)
timeValue = parseTime(cmd, &index); //<-- This returns (WebsTime)-1 in case of failure
if (timeValue >= 0) //<-- If WebsTime is unsigned, this is always true</pre>

</code>
<p>Proposed solution:</p>

<pre><code>
static WebsTime dateParse(WebsTime tip, char *cmd)
{
 WebsTime    parsedValue, dateValue;
int         index, tmpIndex, weekday, timeValue;
 (...)
timeValue = parseTime(cmd, &index); //<-- This returns (WebsTime)-1 in case of failure
if (timeValue != (WebsTime)-1) //<-- If WebsTime is unsigned, this is usigned as well</pre>

</code>

**Comment by embedthis** [comment]
But parseTime is defined to return an "int" not a WebsTime.

It does not return a time_t, rather it returns:

            returnValue = (((hourValue * 60) + minuteValue) * 60) + secondValue;

If this is negative, there is an error.

Can you provide an actual if-modified-since header that demonstrates the issue.

Thanks

**Comment by przem312** [comment]
Sorry, I've quoted the wrong if. 
I meant this one:
<pre><code>
  dateValue = parseDate1or2(cmd, &tmpIndex);
        if (dateValue >= 0) {
</code>
Where:
<code>
static WebsTime parseDate1or2(char *buf, int *index) 
{
    /*  
        Format of buf is either
            2DIGIT SP month SP 4DIGIT
        or
            2DIGIT "-" month "-" 2DIGIT
     */
    WebsTime    returnValue;
    int         dayValue, monthValue, yearValue, tmpIndex;

    returnValue = (WebsTime) -1;
    tmpIndex = *index;
</code>
</pre>
We are using standard format returned by asctime(), so we should take parseDate3Time() path, but we've taken this one.

**Comment by embedthis** [comment]
Thanks for clarifying.

**Comment by embedthis** [comment]
This is a bug.

To correct, we are backporting the date/time parsing code from Appweb which is smaller, faster and more flexible.
