### ISSUE TITLE
Weird http status on modified http request

### ISSUE THREAD

**Issue by przem312** [embedthis/goahead#166]
<h3>Environment</h3>

<p>GoAhead Version: 3.4.6<br>
O/S: VxWorks 5.9<br>

<h3>Problem Description:</h3>

<p>During tests of our webservice we performed a manual telnet test with following request:</p>
<pre><code>
..... .....'.........GET /index.html HTTP/1.0
</code></pre>
<p>Server responded with following values:</p>

<pre><code>
HTTP/1.0 <b>262544</b> Internal Server Error
Date: THU JAN 01 02:31:45 1998
Content-Length: 0
Connection: close
Content-Type: text/html
X-Frame-Options: SAMEORIGIN

</code></pre>
<p> We haven't looked into goAhead code thoroughly, but we believe this value is random and read out of uninitialized variable.</p>

**Comment by embedthis** [comment]
Not random, that is the WEBS_NOLOG flag.

What version of GoAhead are you using?  The current code looks like it masks that flag out and you get a correct 400 status.
