### ISSUE TITLE
Memory leak on unknown HTTP proto version

### ISSUE THREAD

**Issue by przem312** [embedthis/goahead#167]
<h3>Environment</h3>

<p>GoAhead Version: 3.4.6<br>
O/S: VxWorks 5.9<br>

<h3>Problem Description:</h3>

<p>During tests of our webservice we performed a manual test with following request:</p>
<pre><code>
MESSAGE = 'GET / HTTP <b>2.0</b> \r\n'
</code></pre>
<p>After numerous number of handled requests we ran out of heap.</p>
<p> Problem lies in function responsible for parsing header:
<pre><code>
 wp->filename = sfmt("%s%s", websGetDocuments(), wp->path);
    wp->query = sclone(query);
    wp->host = sclone(host);
    wp->protocol = wp->flags & WEBS_SECURE ? "https" : "http";
    if (smatch(protoVer, "HTTP/1.1")) {
        wp->flags |= WEBS_KEEP_ALIVE | WEBS_HTTP11;
    } else if (smatch(protoVer, "HTTP/1.0")) {
        wp->flags &= ~(WEBS_HTTP11);
    } else {
        <b>protoVer = sclone("HTTP/1.1");</b>
        websError(wp, WEBS_CLOSE | HTTP_CODE_NOT_ACCEPTABLE, "Unsupported HTTP protocol");
    }
    wp->protoVersion = sclone(protoVer);
    if ((listenPort = socketGetPort(wp->listenSid)) >= 0) {
        wp->port = listenPort;
    } else {
        wp->port = atoi(port);
    }
    wfree(buf);
</code></pre>
<p>The buffer for <code> <b>protoVer = sclone("HTTP/1.1");</b></code> is never freed.</p>

**Comment by embedthis** [comment]
Nice pick up.

Note: that should never happen as HTTP/1.0 or HTTP/1.1 should be the protocol. But good to fix regardless.

**Comment by przem312** [comment]
There is another leak in this function. websError allocates string to  wp->protoVersion and then   wp->protoVersion = sclone(protoVer); overwrites it.

**Comment by embedthis** [comment]
What tool are you using to find these?
