### ISSUE TITLE
Memory leak in websAllocSession

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#172]
websAllocSession in http.c line 3045 leaks memory if hashCreate fails.
This affects versions up to 3.5.0 at least

     if ((sp->cache = hashCreate(WEBS_SESSION_HASH)) == 0) {
         wfree(sp); // <<<<<<<<<<<<<<<<< this should be added
         return 0;
     }

**Comment by przem312** [comment]
double leak. sp->id is allocated dynamically as well.
