### ISSUE TITLE
websAddRoute leaks memory

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#173]
websAddRoute in route.c line 304 leaks memory.
Affects versions up to 3.5.0 at least:

     if ((key = hashLookup(handlers, handler)) == 0) {
        error("Cannot find route handler %s", handler);
        wfree(route); // <<<<<<<<< this line should be added
        return 0;
     }

**Comment by przem312** [comment]
actually, there's a double leak. 
route->prefix is allocated dynamically as well.
