### ISSUE TITLE
const correctness in API functions

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#179]
The API should be designed for const-correctness. Example:
PUBLIC void websSetVar(Webs _wp, char *var, char *value)
should have const char_ var and const char\* value.
Otherwise, one has to cast away constness from rom-tables which is extremely irritating.

**Comment by embedthis** [comment]
The entire API does not use const and could on many APIs. Unfortunately, adding const often then requires that other data and APIs be converted to use const. We'll do this in the future, but it will be a big, wholesale change to the API to add const to all applicable APIs.

**Comment by mobrien** [comment]
Version 4 adds const to most APIs.
