### ISSUE TITLE
Default page is not loaded if fs is located in ROM-FS

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#182]
The default page is not loaded, if ME_ROM is used, as websStatFile forgets to remove the trailing '/' from the URL in case the FS is not WINDOWS.
My bugfix for fs.c looks like this (avoiding a copy of the filename as the Windows version does):

    PUBLIC int websStatFile(char *path, WebsFileInfo *sbuf)
    {
    #if ME_ROM
    WebsRomIndex    *wip;
    WebsKey         *sp;

    assert(path && *path);

	int nchars = strlen(path);
	char name[ME_GOAHEAD_LIMIT_FILENAME];
	if (path[nchars - 1] == '/' || path[nchars - 1] == '\\')
	{
		strncpy(name, path, ME_GOAHEAD_LIMIT_FILENAME);
    
		name[--nchars] = '\0';
		path = name;
	}

**Comment by embedthis** [comment]
Can you retest with the "dev" branch. Some changes were recently made that should fix this.

In particular, webcomp now makes all files absolute paths. Make sure you have directory entries in the rom-documents file. After the name, they should be all zeros.

**Comment by Isarhamster** [comment]
dev branch works great - I assume that the changes make it into 3.5.1, so I close this issue.
