### ISSUE TITLE
Code in js.c exposes freed memory to calling stack frames

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#190]
In the module js.c, function parseStmt, the following code exposes freed memory to upper stack frames:

            ep->func = &func;

            setString(&ep->result, "");
            if (jsLexGetToken(ep, state) != TOK_LPAREN) {
                freeFunc(&func);
                goto error;
            }

After calling freeFunc, 

           ep->func = saveFunc;

should be inserted to avoid this exposure.

**Comment by embedthis** [comment]
Do you mean:

```
            setString(&ep->result, "");
            if (jsLexGetToken(ep, state) != TOK_LPAREN) {
                freeFunc(&func);
                ep->func = saveFunc;
                goto error;
            }
```

**Comment by Isarhamster** [comment]
Yes
