### ISSUE TITLE
Memory leak in websNormalizeUriPath()

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#197]
There is a possibility of memory leak in `websNormalizeUriPath` function ([http.c line 2701](https://github.com/embedthis/goahead/blob/d560e9b6f8fa3dc907cdcb65a6c469d799ab29b7/src/http.c#L2701))

```cpp
    if ((dupPath = walloc(len + 2)) == 0) {
        return NULL;
    }
    strcpy(dupPath, pathArg);

    if ((segments = walloc(sizeof(char*) * (len + 1))) == 0) {
        return NULL;
        // !!! LEAK: variable `dupPath` not freed
    }
```

Note that this only happens when `walloc` fails, but allocated memory should be still handled properly.

**Comment by embedthis** [comment]
Code now reads:

```
    if ((segments = walloc(sizeof(char*) * (len + 1))) == 0) {
        wfree(dupPath);
        return NULL;
    }
```
