### ISSUE TITLE
NULL pointer dereference in websParseDateTime()

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#200]
When certain conditions are met (code is pretty complicated) there is a possibility to dereference NULL pointer in function `websParseDateTime` ([time.c line 372](https://github.com/embedthis/goahead/blob/49df113b68332b37d03629e568cdce51169fa868/src/time.c#L372))

```cpp
            negate = *cp == '-' ? -1 : 1;
            // !!! Variable `cp` can be NULL
```

Because this code is used to parse HTTP headers, this issue can be probably used to crash GoAhead if header is manipulated by an attacker.

**Comment by embedthis** [comment]
Code now reads:

```
            if (token[0] == '-' || token[0] == '+') {
                negate = *token == '-' ? -1 : 1;
                token++;
            } else {
                negate = 1;
            }
```
