### ISSUE TITLE
Scanning Go-ahead using OpenVAS Scanner

### ISSUE THREAD

**Issue by ssale** [embedthis/goahead#201]
Hi,
We are testing go-ahead 1.162(very older) and there are few memory leaks.

We are testing against vulnerability scanner called openVAS. For every scan of openvas we see there is 3%(3mb) memory leaks. The memory leaks happened in goahead webserver process.

We have not seen any help on site.could you please help on this.
We can not update this to latest...

Thanks in advance.

**Comment by embedthis** [comment]
That is a very ancient version of GoAhead (~1997). There are some leaks and vulnerabilities with that old version. We do not support 1.X and only support 3.x. 

You could contact embedthis for custom dev services, but a better path would be to upgrade somehow.

**Comment by ssale** [comment]
Can we see some fixes for version 1.X ?

**Comment by embedthis** [comment]
You'll have to do that yourself by comparing the source for 1.X and 3.X.
