### ISSUE TITLE
Large request with 'Transfer-Encoding: Chunked' causes GoAhead to hang

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#202]
It is possible to hang GoAhead using sufficiently large request with `Transfer-Encoding: Chunked`. Required size depends on input buffer size. Maximum size of input buffer is `ME_GOAHEAD_LIMIT_PUT + 1` ([http.c line 405](https://github.com/embedthis/goahead/blob/516c8c9c3d5adbc7703651a6f3b19fc592e28626/src/http.c#L405)).

If during chunked transfer input buffer is exhausted code hangs in endless loop. This happens in function `filterChunkData` ([http.c line 1229](https://github.com/embedthis/goahead/blob/516c8c9c3d5adbc7703651a6f3b19fc592e28626/src/http.c#L1229)):

```cpp
        case WEBS_CHUNK_DATA:
            len = min(bufLen(rxbuf), wp->rxRemaining); // <= `len` > 0
            nbytes = min(bufRoom(&wp->input), len); // <= `nbytes` = 0
            nbytes = bufPutBlk(&wp->input, rxbuf->servp, nbytes); // <= nothing copied, `nbytes` = 0
            bufAddNull(&wp->input); // <= silently fails to grow buffer
            bufAdjustStart(rxbuf, nbytes);
            wp->rxRemaining -= nbytes;  // <= `rxRemaining` not decreased
            if (wp->rxRemaining <= 0) { // <= false
                wp->rxChunkState = WEBS_CHUNK_START; // <= state not changed
                bufCompact(rxbuf);
            }
```

When there is no space in input buffer, `nbytes` will be 0. This means `wp->rxRemaining` will not be decreased and `wp->rxChunkState` will not be changed. This creates infinite loop.

**Comment by embedthis** [comment]
Where is the infinite loop exactly?

If there is no input left, then the top of the loop should break.

        while (bufLen(rxbuf) > 0) {

rxbuf will be empty and the code will break from the loop and wait for an I/O event with a new block of input.

**Comment by endrjux** [comment]
But there is still some input left, `bufLen(rxbuf)` is greater than zero. `wp->input` is exhausted (can't grow) so that `rxbuf` can't be copied to `wp->input` and data is left in `rxbuf`.

**Comment by embedthis** [comment]
Thanks that helps.

Did you change the default limits?  readEvent should make sure there is ME_GOAHEAD_LIMIT_BUFFER available and websRead will only read ME_GOAHEAD_LIMIT_BUFFER, so this condition should not happen (but clearly is). Did you modify the ME_GOAHEAD_LIMIT_BUFFER or other limits from their defaults?

I'd like to understand more how this can happen.

**Comment by endrjux** [comment]
`ME_GOAHEAD_LIMIT_BUFFER` is set to its default value of 1024. I changed `ME_GOAHEAD_LIMIT_PUT` from 200M to 32k (or 16k, or 8k, smaller buffer causes this issue to trigger faster).

**Comment by embedthis** [comment]
The issue looks like reducing ME_GOAHEAD_LIMIT_PUT means the wp->input buffer cannot grow when you upload a request larger than this amount. This should at least trigger an error if you upload a request larger than the configured PUT limit.
```
diff --git a/src/http.c b/src/http.c
index b81429d..1c117e5 100644
--- a/src/http.c
+++ b/src/http.c
@@ -1308,7 +1308,10 @@ static bool filterChunkData(Webs *wp)
         case WEBS_CHUNK_DATA:
             len = min(bufLen(rxbuf), wp->rxRemaining);
             nbytes = min(bufRoom(&wp->input), len);
-            nbytes = bufPutBlk(&wp->input, rxbuf->servp, nbytes);
+            if (len > 0 && (nbytes = bufPutBlk(&wp->input, rxbuf->servp, nbytes)) == 0) {
+                websError(wp, HTTP_CODE_REQUEST_TOO_LARGE | WEBS_CLOSE, "Too big");
+                return 1;
+            }
             bufAddNull(&wp->input);
             bufAdjustStart(rxbuf, nbytes);
             wp->rxRemaining -= nbytes;
```

**Comment by endrjux** [comment]
This error will happen even with default input buffer size, just later. One can just transfer chunks indefinitely till  `wp->input` is exhausted. The default limit is just very large. (This also means that with default buffer size, GoAehad with consume very large amount of memory in this situation)

Adding above check solves the issue.
