### ISSUE TITLE
Compilation error when upload is disabled.

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#206]
There is a compilation error in [http.c line 451](https://github.com/embedthis/goahead/blob/516c8c9c3d5adbc7703651a6f3b19fc592e28626/src/http.c#L451) when upload is disabled (`ME_GOAHEAD_UPLOAD` set to 0). There is no member `clientFilename` in `wp` structure.

**Comment by endrjux** [comment]
Issue is closed but code wasn't fixed. Why?

**Comment by embedthis** [comment]
Confusion with a related issue when upload and rom are enabled. Reopening.
