### ISSUE TITLE
`chdir` and `getcwd` used even if ME_ROM is defined

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#212]
Filesystem functions `chdir` ([goahead.c line 76](https://github.com/embedthis/goahead/blob/ac367d7a2884aa150cdfc0495348fd886d3bd228/src/goahead.c#L76)) and `getcwd`  ([goahead.c line 169](https://github.com/embedthis/goahead/blob/ac367d7a2884aa150cdfc0495348fd886d3bd228/src/goahead.c#L169)) are used even if `ME_ROM` is defined. I think support for those functions should not be expected if there is no support for filesystem at all. Also, the second place (`logHeader` function) shouldn't be compiled when logging is disabled (see #210)

**Comment by embedthis** [comment]
There are two use cases for the ROM file system support.

1. Where users don't have a file system

2. Where users have a file system but want to lock down the web content in ROM

So we still support chdir and getcwd as they may be needed for (2)

**Comment by endrjux** [comment]
I understand that it's needed for (2) and it's ok, but users (1) can't compile (link actually) GoAhead then. Maybe it should be enabled conditionally so that use case (1) is still possible.

**Comment by endrjux** [comment]
Missclick, sorry.

**Comment by embedthis** [comment]
What O/S are you referring to. If someone is porting to a new O/S, they can stub these as they'll undoubtably have other source changes to do.

**Comment by endrjux** [comment]
Sure, stubs are fine. You are right - OSes not supported in osdep.h/c will require some custom code anyway.
