### ISSUE TITLE
How to use the Goahead test?

### ISSUE THREAD

**Issue by HuangXiHans** [embedthis/goahead#216]
I want to study the goahead webserver for my company's projects, but I do not know how to start. I download the codes, but I do not know how to running the test samples. Now, I already port the goahead to my RTOS, and can running now, but I do not know how to use the samples, and you can supply some good advices to me, or tell me a good book. Thanks.

**Comment by embedthis** [comment]
Sorry, there is not a good book or many samples.

The code is pretty readable and the test/* code does provide some examples.

Thanks

Michael


Michael O'Brien
Embedthis Software
mob@embedthis.com
http://embedthis.com
http://twitter.com/embedthat
