### ISSUE TITLE
Security issue: Session fixation attack

### ISSUE THREAD

**Issue by raintung** [embedthis/goahead#218]
websAllocSession will allocate the session ID. For existing session ID, websAllocSession will reuse the session ID. It can cause the session fixation attack.
The attacker can inject the session ID in the cookie, the victim use this session ID login the site. Because of reusing the session ID, the attacker can control the victim session.

**Comment by embedthis** [comment]
Web apps are stateless, each request is unique and cookies are used to string together a set of requests into a session by storing some session state on the server that is indexed by the session cookie. It is essential that the session cookie be protected over SSL. If the session cookie is intercepted while the user is actively using the session then bogus requests can be issued and the server can never tell them apart from the original. So it is imperative to secure the session cookie.

The existing login mechanism could be improved as you point out by forcing a new session to be created on login AND by destroying the session on logout. We'll add this in the next patch as a priority.

The "fixation" exposure to this only occurs if you do not adequately secure the session cookie.

**Comment by raintung** [comment]
Actually secure the session cookie over SSL, it isn't enough. Web apps can't make sure the site don't have XSS vulnerability. XSS vulnerability can easy inject the cookie by JS. 
I don't understand why reuse the session ID. Just make new, I don't think it is problem. Performance? or others? Make a new session ID, at least hacker can't inject the invalid session ID and control the victim session. Some web apps will not use login or logout function provider by goahead.
Could add some compile flag to turn on or off the reuse the session ID?

**Comment by embedthis** [comment]
XSS should not be an issue if you use a HTML only cookie over SSL. The cookie should be private and be unreadable by scripts.

Agree that on login, a new session should be created. NOT on each request. Similarly, on logout, the session should be destroyed.

**Comment by raintung** [comment]
Hmm.... Do you talk about HTTPONLY for cookie?
but for https://github.com/embedthis/goahead/issues/219
HTTPONLY doesn't work again.

I inject the cookie use JS in the html(XSS vulnerability), the victim access the html that will inject the Cookie by JS.
Can use path, domain, let inject cookie be first while client send the request.
Cookie:
hack-goahead-session-=hacked; -goahead-session-=::webs.session::434374837834879

Well, now Goahead will get the session ID (strstr logic) is **hacked**. 
OK,  Victim re-login the site because of invalid session ID **hacked**. 

- If NOT renew the session, the **hacked** will be new sessionID because of reuse the session ID.

- If renew the session, the victim need always relogin the site after the socket timeout. It is bad usability.

BTW, some product  will do login or logout function by self, can't make sure will create a new session after login. Usually HTTPONLY + SSL will keep the cookie secure.

**Comment by embedthis** [comment]
Why does httponly not work?

**Comment by raintung** [comment]
goahead get sessionID from cookie
The code:
**_ if (cookie && (value = strstr(cookie, WEBS_SESSION)) != 0) {_**

strstr the method will get the fisrt "-goahead-session-" string position.

Attacker just inject the cookie **hack-goahead-session-=hacked** before goahead session id cookie **-goahead-session-=::webs.session::434374837834879**

Because the HTTPONLY js can't change the session cookie **-goahead-session-**, but attacker can inject the cookie name just include **-goahead-session-**, like **hack-goahead-session-**

Only let  the sequence of cookie **hack-goahead-session-** before **-goahead-session-**. Goahead will get the sessionID from cookie **hack-goahead-session-** .

**Comment by embedthis** [comment]
Okay, understand. You are adding both issues together to provide the scenario. Thanks.

Both will be addressed in the next update.
