### ISSUE TITLE
Security issue: Get the Session ID vulnerability

### ISSUE THREAD

**Issue by raintung** [embedthis/goahead#219]
websGetSessionID only invoke the strstr(cookie, WEBS_SESSION)) != 0 to get the session ID from cookie, it is very easy to get the wrong session ID bypass the special the Cookie
ex.
hack-goahead-session-=hacked; -goahead-session-=::webs.session::434374837834879
or.
hacked=hack-goahead-session-=hacked; -goahead-session-=::webs.session::434374837834879

Even if the cookie  -goahead-session- has HTTPONLY secure property, it still can inject the session ID as the example as above. 
The attacker can control the session ID if the site has XSS vulnerability.

**Comment by embedthis** [comment]
Can you explain a little more.

That session ID would still need to be a valid session ID and an attacker would have needed to compromise the browser or network to gain access to it. If they can do either of these two, then they can simply use the session cookie directly. Prefixes does not gain anything?  Can you please explain your reasoning a bit more.

**Comment by embedthis** [comment]
We are updating the cookie parsing to use exact matching and not strstr.
