### ISSUE TITLE
Change if block to do block in BPUT macro

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#221]
`BPUT` and `BPUTNULL` macros use `if(1) { ... } else` for protection. This causes GCC to emit a lot of warnings:
> suggest braces around empty body in an 'else' statement

Moreover if semicolon is omitted by mistake, `else` will silently swallow next line after `BPUT`.
This could be changed to safer and warning-free `do { ... } while(0)`.

**Comment by embedthis** [comment]
What compiler, platform versions. Please read: 

#111

**Comment by endrjux** [comment]
The warning is:

> suggest braces around empty body in an 'else' statement

Compiler is: GCC 4.3.3 for ARM, `-Wall` option is used for compilation.

That code is dangerous, regardless of warning. If semicolon is accidentally omitted, the code will compile and one line after `BPUT` will be silently discarded.

**Comment by embedthis** [comment]
Thanks for the details.

We disagree that this code is dangerous. The BPUT code is not part of the public API, it is internal to this function. The BPUT() functions identically to any C statement and as such, requires a terminating semicolon after it.

But your suggestion of do { ... } while(0) is neat and we'll check that out.

**Comment by embedthis** [comment]
Added do/while pattern to dev branch.
