### ISSUE TITLE
WebsRomIndex.pos not initialized

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#222]
For some reason default rom.c and that created by webcomp are not initializing 4th member of `WebsRomIndex` (member `pos`).
```
WebsRomIndex websRomIndex[] = {
	{ 0, 0, 0 }
};
```
should be
```
WebsRomIndex websRomIndex[] = {
	{ 0, 0, 0, 0 }
};
```
And so on.
This is not some critical bug, but GCC issues a warning. ;-)

**Comment by endrjux** [comment]
Why was this closed without fix? :-)

**Comment by embedthis** [comment]
Not without a fix. Our process is to marked fixed when the code is committed to the dev branch. 

Preparing release now.

**Comment by endrjux** [comment]
Ok, I understand. :-)
