### ISSUE TITLE
TimeToken, masking and negative integers

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#223]
I think there is something wrong with handling of negative TimeToken.value variables. Variables `zones` and `offsets` use masked negative values.
Consider `lookupSym` function from time.c:
```cpp
static int lookupSym(char *token, int kind)
{
    // ...
    // suppose value is negative
    // For example in
    // { "pst",  -480 | TOKEN_ZONE}
    //  (-480 | TOKEN_ZONE) equals -480 (!)
    // -480       = 0xFFFFFe20
    // TOKEN_ZONE = 0x04000000
    // result     = 0xFFFFFe20
    if (kind != (tt->value & TOKEN_MASK)) {
    // kind and value are signed, TOKEN_MASK is unsigned (!)
    // (tt->value & TOKEN_MASK) equals TOKEN_MASK
    // GCC issues warning about comparison of signed and unsigned (!)
    // tt->value  = 0xFFFFFe20
    // TOKEN_MASK = 0xFF000000
    // result     = 0xFF000000
    // kind       = 0x04000000
    // condition is false but it's expected to be true
        return -1;
    }
    // even if above would pass somehow
    // (tt->value & ~TOKEN_MASK) is large, positive, unsigned int
    // certainly not original value (-480)
    // TOKEN_MASK = 0xFF000000
    // tt->value  = 0xFFFFFe20
    // result     = 0x00FFFe20
    return tt->value & ~TOKEN_MASK;
}
```
(Example: http://ideone.com/TqXUSe)

Please note that if integers are 32 bit (common case) `0xFF000000` literal will have `unsigned int` type, not `signed int`. All above also assumes two's complement (common case) signed arithmetic.

**Comment by embedthis** [comment]
What platform, CPU and compiler are you using.

**Comment by endrjux** [comment]
GCC compiler for ARM.

The problem is `-480 | 0x04000000` equals `-480` but GoAhead code expects it to "encode" token type in the most significant byte. This is impossible, because in negative two's complement number this most significant byte will be all ones. You can't use OR to change ones to zeros.

Then GoAhead tries to extract this token type, but it is not there.

Please see http://ideone.com/TqXUSe

**Comment by embedthis** [comment]
Got it. Thanks.

**Comment by endrjux** [comment]
Looks good now. Thanks.
