### ISSUE TITLE
fileWriteEvent error checking

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#227]
Consider following [piece of code from fileWriteEvent function](https://github.com/embedthis/goahead/blob/8b084ed3fc2378c5df37bc4d8507fd8f2f7e5b1c/src/file.c#L124):
```cpp
        if ((wrote = websWriteSocket(wp, buf, len)) < 0) {
            /* May be an error or just socket full (EAGAIN) */
            websPageSeek(wp, -len, SEEK_CUR);
            break;
        }
```
If no bytes were written, `EAGAIN` is assumed. But this may not be the case - there might be a socket error in `websWriteSocket`. This is not checked and causes retries over and over again, even when there is no point in retrying. In case of error, that "retry loop" will be ended by a timeout.

I was able to "hang" GoAhead for a timeout period when connections were limited to one or two. This happened when one side of connection (Internet Explorer) closed the socket in the middle of page transfer. Error is reported, but above code assumes `EAGAIN` and tries over and over again.

Error should be checked like in [websFlush function](https://github.com/embedthis/goahead/blob/21727ba800e6c546d1d1b6eb8f892a822299d37e/src/http.c#L2061). At least this is what I used to fix that.

**Comment by endrjux** [comment]
Are you sure 451d09b3df73631247716179df57f21919e08154 solves this? Now there is no `websPageSeek` in case of error, but retry loop is still not terminated I think. `websFlush` does `wp->state = WEBS_COMPLETE;` when error occurs.
Just asking. ;-)

**Comment by embedthis** [comment]
Added setting WEBS_COMPLETE.

Thank you for the tip
