### ISSUE TITLE
Installation under Mac OS incomplete

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#229]
### Environment
1. O/S Version: Mac-OS 10.11.5
2. GoAhead Version: 3.6.3
3. Hardware: Intel
### Problem Description:

After compiling goAhead out of the box (which works extremely well!) sudo make install forgets to install
/etc/goahead/self.key and /etc/goahead/self.cert. Adding these would make it easier for newbies to start goahead instantly.

**Comment by embedthis** [comment]
Thanks for the suggestion.

Currently we deliberately don't do that be cause we REALLY don't want people to use the self.* cert and key. Everyone should get or generate their own certificates. Making it too easy encourages people to take the easy route and use these files. Which is really bad for security.

**Comment by Isarhamster** [comment]
In this case, the make file should echo proper instructions - currently, after make install it is suggested to start the server, which does not work. Also I don't need certs and keys, I just want a simple web-page. Why do I need these files in this case?

**Comment by mobrien** [comment]
Rethink: given the warnings by browsers, we are going to install the self.* certificates as you suggest in 4.0.0.
