### ISSUE TITLE
Goahead webserver memory usage continue increase

### ISSUE THREAD

**Issue by shaileshpanchal** [embedthis/goahead#230]
### Environment
1. O/S Version:  OpenSuse 13.1
2. GoAhead Version:  3.4.4
3. Hardware:  Intel Process
### Build
1. If built from source, what was your configure command line:

```
To clean
make CC=gcc ME_COM_EST=0 ME_COM_OPENSSL=0 ME_COM_NANOSSL=0 ME_COM_SSL=0 ME_GOAHEAD_CGI=1 ME_ROM=0 ME_COM_AUTH=0 ME_GOAHEAD_AUTH=0 ME_GOAHEAD_UPLOAD=0 ME_GOAHEAD_DIGEST=0 ME_GOAHEAD_JAVASCRIPT=0 clean

To compile

make CC=gcc ME_COM_EST=0 ME_COM_OPENSSL=0 ME_COM_NANOSSL=0 ME_COM_SSL=0 ME_GOAHEAD_CGI=1 ME_ROM=0 ME_COM_AUTH=0 ME_GOAHEAD_AUTH=0 ME_GOAHEAD_UPLOAD=0 ME_GOAHEAD_DIGEST=0 ME_GOAHEAD_JAVASCRIPT=0 all
```
### Problem Description:

Hi All, 
I have configure and install goahead webserver on opensuse OS version PC.  When remote PC or user was create the more then 12 web connection with server then memory leakage was started. All connection was free by goahead webserver but memory footprint was not decrease. If I was create the more then 100 connection with webserver then it was consume lots of memory which are never get free again.

Regards,
Shailesh Panchal

**Comment by sensedeep** [comment]
Memory may not decrease due to normal C malloc memory fragmentation. Does memory continue to go up?  If you run for several hours, what is the peak?

Please provide more actual numbers. We need to see unlimited growth of memory over time to indicate a leak. 

Then we need to see the actual request that is doing this. Is this for a static file, or are you running any custom code in response to the request.

**Comment by kimi8187** [comment]
Env:
O/S Version: Linux version 3.4.11-rt19
GoAhead Version: 3.6.3
Hardware: MIPS
actually with env upside, I met the same problem, with LOIC(Low Orbit Ion Cannon) start 1000 threads no wait for reply continuously attack port 443 of the device, the memory usage of goahead continue increase, after stop attack, the memory usage does not decrease all the time. At the beginning check the head of gohead process, only hundreds of KBs, but with LOIC's attack, it will increase to 100+M.
top result like this
`Mem: 212236K used, 18584K free, 0K shrd, 0K buff, 46448K cached
CPU:   7% usr   4% sys   0% nic  87% idle   0% io   0% irq   0% sirq
Load average: 1.27 1.12 1.13 2/173 20830
  PID  PPID USER     STAT   VSZ %MEM CPU %CPU COMMAND
20674   768 root     S     170m  76%   1   9% /usrapp/goahead`

**Comment by mobrien** [comment]
Fixed by patch - thank you.
