### ISSUE TITLE
websWriteSocket error is not always an error

### ISSUE THREAD

**Issue by endrjux** [embedthis/goahead#231]
Function `websWriteSocket` returns `-1` on socket error. But it can also return `-1` when webs/socket flags `WEBS_CLOSED` or `SOCKET_EOF` are set. Functions that use `websWriteSocket` - `fileWriteEvent` and `websFlush` assume that `-1` means socket error and don't check if it's in fact webs/socket flag. Additional `if` with those two flags should be added before call to `socketGetError`. If true reason of `-1` result is certain flag being set and not socket error, `socketGetError` will return some previous, unrelated socket error which can be `EWOULDBLOCK` or `EAGAIN`

For example `websFlush` might read:

``` cpp
// ...
if ((written = websWriteSocket(wp, op->servp, nbytes)) < 0) {
    // `sp` acquired previusly using socketPtr(wp->sid)
    if (((sp->flags & SOCKET_EOF) == 0) && ((wp->flags & WEBS_CLOSED) == 0)) { // <-- ADDED
        errCode = socketGetError();
        if (errCode == EWOULDBLOCK || errCode == EAGAIN) {
            /* Not an error */
            written = 0;
            break;
        }
    }
    /*
        Connection Error
     */
    wp->flags &= ~WEBS_KEEP_ALIVE;
    bufFlush(op);
    wp->state = WEBS_COMPLETE;
    break;
}
// ...
```

We could trigger such scenario (`-1` result and flag set without socket error) during massive storm of malformed HTTP traffic. It ended in sockets in CLOSE_WAIT state that were never closed properly. This resulted in resources exhaustion.

**Comment by embedthis** [comment]
Actually, I think they do check. fileWriteEvent tests socketGetError and if EWOULDBLOCK or EAGAIN, it continues with the request. Otherwise, it completes the request.

If SOCKET_EOF or WEBS_CLOSED and there is more data to write, that is an error and the request should be completed and not more data should be attempted to be written.

**Comment by endrjux** [comment]
You can't call `socketGetError()` if there is no error on the socket. Otherwise you get some unrelated error code. This is the main problem here.

In other words - if ` SOCKET_EOF` or `WEBS_CLOSED` flags are set, call to `socketGetError()` returns meaningless value which is treated as real socket error.
