### ISSUE TITLE
Upload file security: Abnormal header protocol case the memory and system resource leak

### ISSUE THREAD

**Issue by raintung** [embedthis/goahead#233]
### Environment
1. O/S Version: Linux
2. GoAhead Version:  3.6.3
3. Hardware: 
### Problem Description:
Upload the file, and send the Abnormal header protocol:

Content-Disposition: form-data; name="field1"; filename="user.file"; filename="user.file"; filename="user.file"; filename="user.file"; filename="user.file".....

upload.c method: processUploadHeader
```
 if ((wp->uploadTmp = **websTempFile(uploadDir, "tmp")**) == 0) {
                    websError(wp, HTTP_CODE_INTERNAL_SERVER_ERROR,
                        "Cannot create upload temp file %s. Check upload temp dir %s", wp->uploadTmp, uploadDir);
                    return;
                }
                trace(5, "File upload of: %s stored as %s", wp->clientFilename, wp->uploadTmp);

                if ((wp->upfd = open(wp->uploadTmp, O_WRONLY | O_CREAT | O_TRUNC | O_BINARY, 0600)) < 0) {
                    websError(wp, HTTP_CODE_INTERNAL_SERVER_ERROR, "Cannot open upload temp file %s", wp->uploadTmp);
                    return;
                }
                /*
                    Create the files[id]
                 */
                **file** = wp->currentFile = walloc(sizeof(WebsUpload));
                memset(file, 0, sizeof(WebsUpload));
                file->clientFilename = sclone(wp->clientFilename);
                file->filename = sclone(wp->uploadTmp);
```

will create a lot of temfile in the system and also not free the file memory

**Comment by sensedeep** [comment]
Can you please post the HTTP headers for the request and response from the GoAhead log.

**Comment by raintung** [comment]
I don't understand why need post the log. It isn't normal HTTP upload....
Usually standard HTTP upload protocol 
POST /b.asp HTTP/1.1
Accept: */*
Accept-Language: zh-cn
Content-Type: multipart/form-data; boundary=---------------------------40612316912668
.....
-----------------------------40612316912668
Content-Disposition: form-data; name="c"; filename="test.txt"
Content-Type: text/plain

aaaa
abbb
cdd
ccc
-----------------------------40612316912668
But I change this protocol, let Content-Disposition: form-data; name="c"; filename="test.txt"; filename="test.txt";filename="test.txt";filename="test.txt";

It is abnormal protocol attack, it cause the server memory leak and a lot of temp file.

**Comment by raintung** [comment]
Yes, if have duplicate the filename, should end of the request because it is abnormal, and just release the resource. I think it is ok.

**Comment by mobrien** [comment]
Thanks for the suggested fixed.
