### ISSUE TITLE
Missing test for working time() breaks client cache in Chrome and IE

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#234]
If time() is not provided by the embedded OS, time() will not disappear (creating a linker error) but will permanently return `(time_t)-1` as mandated by the ISO C standard.
This is hard to detect, as the only effect is broken caching in Chrome and IE, but not in Firefox.

Thus somewhere in the startup code, goahead should have something like `ASSERT(time()!=(time_t)-1);`.

**Comment by mobrien** [comment]
Why will you not get a linker error?

Surely that is the clue?

**Comment by Isarhamster** [comment]
A operating system that cannot provide time still has to have a time() function, but this function simply returns -1. This is the POSIX standard requirement. So you can't get a linker error, but you will get trouble during runtime.
