### ISSUE TITLE
Client/Server Caching (code 304) broken if ME_ROM is defined

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#235]
Bug 1: If ME_ROM is defined, fs.c in `websStatFile()` forgets to set the `sbuf->mtime` member to a valid value but instead sets it to 0. This runs into
Bug 2: fs.c `filehandler()` has a line
`if (wp->since && info.mtime <= wp->since)`
As Bug 1 delivers the value 0 to the client, the client will send as last modification date 1970-1-1 which is a perfect date, but is converted into `wp->since==0`. Thus the code 304 is never delivered. 

In effect, all caching in IE as Client is inhibited (Firefox/Chrome are somewhat more tolerant if the Date field in the response is correctly set).

**Comment by mobrien** [comment]
What did you end up doing?

We could set mtime to 1?

**Comment by Isarhamster** [comment]
My project had the compilation date compiled in so I invented a function websRomTime() which returned this compilation time (which is updated for each build). This has the advantage, that if I install a new firmware into my embedded device, the clients all refresh their caches. Simply returning 1 would require that users clean their caches after updating firmware.

**Comment by mobrien** [comment]
Sounds like a neat solution

**Comment by mobrien** [comment]
We've generalized this a little for 4.0.0.

main.me has a "romTime" definition that results in the C define ME_ROM_TIME. 

By setting romTime to the modification time you want for your files, websStatFile will use this modification time. 

You need to run configure then build to update ME_ROM_TIME in me.h.
