### ISSUE TITLE
socketGetError interface lacks sid parameter

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#236]
In environments where the socket error is not stored in a TLS error variable (`errno`) but can be retrieved from the socket interface, the sid is required to get this information.
Thus socketGetError should have the interface `PUBLIC int socketGetError(int sid)` where sid can be ignored in case the socket stack stores errors in thread local storage.
If errno is not TLS but global, errno is extremely dangerous anyhow.
(This is somewhat related with issue #231)

**Comment by mobrien** [comment]
Easy to do this.
