### ISSUE TITLE
checkTimeout closes sessions before WEBS_TIMEOUT expires

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#237]
`http.c::checkTimeout()` is called from two possible timer sources: WEBS_TIMEOUT and PARSE_TIMEOUT. Thus checkTimeout has the habit of dumping sessions that are still in use due to the following lines
```
    if (wp->state == WEBS_BEGIN)
    {
        complete(wp, 0);
        websFree(wp);
        return;
    }
    if (elapsed >= WEBS_TIMEOUT)
    {
```

The test for elapsed should be pulled in front of the first test to avoid premature closing of sessions. Correct code should be 
```
    if (elapsed >= WEBS_TIMEOUT)
    {
        if (wp->state == WEBS_BEGIN)
        {
            complete(wp, 0);
            websFree(wp);
            return;
        }
```

**Comment by mobrien** [comment]
But when called from PARSE_TIMEOUT -- the state will be BEGIN and you want to kill that request because it is too slow. That is the purpose of the parse timeout.

Can you please explain a bit more?

**Comment by Isarhamster** [comment]
You will get into trouble with PARSE_TIMEOUT if the webpage is refreshed lets say every 15 seconds with a meta-refresh and the web page has images and scripts so that parallel loading is enabled. Just browse the page and wait until the page is not refreshed anymore. In case of embedded devices, this is very annoying. The refreshing is stopped usually within on hour with one of the images or scripts not getting loaded as a session was dumped.

**Comment by mobrien** [comment]
Sorry this took a while:

Here is a proposed patch:

```
    if (elapsed >= WEBS_TIMEOUT) {
        if (!(wp->flags & WEBS_HEADERS_CREATED)) {
            if (wp->state > WEBS_BEGIN) {
                websError(wp, HTTP_CODE_REQUEST_TIMEOUT, "Request exceeded timeout");
            } else {
                websError(wp, HTTP_CODE_REQUEST_TIMEOUT, "Idle connection closed");
            }
        }
        wp->state = WEBS_COMPLETE;
        complete(wp, 0);
        websFree(wp);
        /* WARNING: wp not valid here */
        return;
    }
```

**Comment by Isarhamster** [comment]
First tests are encouraging - I can't reproduce the issue anymore!

**Comment by mobrien** [comment]
Great, thank you and sorry for the delay in getting to this.
