### ISSUE TITLE
Small Issues with timers

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#238]
Issue 1) `runtime.c::websRunEvents()` mixes up milliseconds and seconds:
`delay = (int) min(s->at - now, MAXINT);`
should read 
`delay = (int) min(s->at - now, MAXINT / 1000);`
as the result is lateron multiplied by 1000 which will overflow.

Issue 2) Variable lifespan from goahead.h is documented as follows:
`int             lifespan;               /**< Session inactivity timeout (msecs) */`
But lifespan is in seconds, thus the comment should be 
`int             lifespan;               /**< Session inactivity timeout (seconds) */`
The wrong comment lead me upon a wrong track when searching bugs inside the server.

**Comment by mobrien** [comment]
Thanks for both these. We've applied them.
