### ISSUE TITLE
Memory Leaks in crypt.c

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#239]
**Leak 1**
Method `PUBLIC char *websCryptPassword(char *password, char *salt, int rounds)` leaks the memory reserved inside the variable key, thus before returning, `wfree(key);` should be inserted.
**Leak 2**
Method `PUBLIC bool websCheckPassword(char *plainTextPassword, char *passwordHash)` leaks the memory allocated when calling `stok(sclone(passwordHash), ":", &tok);`.
Thus this line should be replaced with the following code: 
`   char* pwCopy = sclone(passwordHash);
    stok(pwCopy, ":", &tok);
    wfree(pwCopy);
`

**Comment by mobrien** [comment]
Thanks for #1 

#2 is not right. After the free, you cannot use "tok".

You need:

    char *ph;
    ph = sclone(passwordHash);
    stok(ph, ":", &tok);

Then on all exit paths:

    wfree(ph)
