### ISSUE TITLE
In function sprintfCore(), case for value "'i'" is not terminated by a 'break' statement.

### ISSUE THREAD

**Issue by scomminc** [embedthis/goahead#244]
line 546:

case 'i':
                ;

            case 'd':
                fmt.radix = 10;

**Comment by Isarhamster** [comment]
Never trust static prgram analysis: the case for "i" is stupposed to fall through into the case of "d".
As the upper case is empty, at least lint will not complain. One could think of marking this case with a comment like `//fallthru`  to guide static analysis tools.

**Comment by mobrien** [comment]
Agree on the comment. Applied.
