### ISSUE TITLE
Porting to ESP32

### ISSUE THREAD

**Issue by nkolban** [embedthis/goahead#245]
I am a keen advocate of the ESP32 processor from Espressif.  See ... 

https://leanpub.com/kolban-ESP32

What I would like to do is investigate what it would take to get goahead running on that platform.  I am skilled in ESP32 programming and the ESP32 platform but don't know the internals of goahead.  What I'd love to do is partner with developers of goahead to set up some live sessions and see how far we get with the goal of adding ESP32 as a first class supported member of the goahead platform.

I can be emailed directly at kolban1@kolban.com

Neil Kolban

**Comment by mobrien** [comment]
I suggest you just have a go at it first yourself and see how you go. It has been ported to lots of platforms. If you have a Posix API, it should not be too hard.
