### ISSUE TITLE
'build/linux-arm-default/obj/mbedtls.o' failed

### ISSUE THREAD

**Issue by ChenhuiZhao** [embedthis/goahead#248]
### Environment

O/S Version:  ubuntu16.04-linux

CROSS_COMPILE: aarch64-linux-gun-gcc

 GoAhead Version: V3.6.3

Hardware:  ARCH=arm

### Build

make CC=aarch64-linux-gnu-gcc ARCH=arm

./configure [options]

do not run ./configure

### Problem Description:
zhaochenhui@ubuntu:~/goahead/goahead-3.6.3$ make CC=aarch64-linux-gnu-gcc ARCH=arm
make --no-print-directory -f projects/goahead-linux-default.mk all
      [Info] Use make SHOW=1 to trace executed commands.
   [Compile] build/linux-arm-default/obj/mbedtls.o
/tmp/ccvVFJsG.s: Assembler messages:
/tmp/ccvVFJsG.s:11891: Error: operand 1 should be an integer register -- `ldr r0,[sp,16]'
/tmp/ccvVFJsG.s:11892: Error: operand 1 should be an integer register -- `ldr r1,[sp,8]'
/tmp/ccvVFJsG.s:11893: Error: operand 1 should be an integer register -- `ldr r2,[sp,40]'
/tmp/ccvVFJsG.s:11894: Error: operand 1 should be an integer register -- `ldr r3,[sp,4]'
/tmp/ccvVFJsG.s:11895: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11896: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11897: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11898: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11899: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11900: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11901: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11902: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11903: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11904: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11905: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11906: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11907: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11908: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11909: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11910: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11911: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11912: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11913: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11914: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11915: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11916: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11917: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11918: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11919: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11920: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11921: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11922: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11923: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11924: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11925: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11926: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11927: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11928: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11929: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11930: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11931: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11932: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11933: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11934: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11935: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11936: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11937: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11938: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11939: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11940: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11941: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11942: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11943: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11944: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11945: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11946: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11947: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11948: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11949: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11950: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11951: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11952: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11953: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11954: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11955: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11956: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11957: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11958: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11959: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11960: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11961: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11962: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11963: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11964: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11965: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11966: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11967: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11968: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11969: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11970: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11971: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11972: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11973: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11974: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11975: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11976: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11977: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11978: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11979: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11980: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11981: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11982: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11983: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11984: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11985: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11986: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11987: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11988: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11989: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11990: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11991: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11992: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:11993: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:11994: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:11995: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:11996: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:11997: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:11998: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:11999: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12000: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12001: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12002: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12003: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12004: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12005: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12006: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12007: Error: operand 1 should be an integer register -- `str r2,[sp,40]'
/tmp/ccvVFJsG.s:12008: Error: operand 1 should be an integer register -- `str r1,[sp,8]'
/tmp/ccvVFJsG.s:12009: Error: operand 1 should be an integer register -- `str r0,[sp,16]'
/tmp/ccvVFJsG.s:12028: Error: operand 1 should be an integer register -- `ldr r0,[sp,16]'
/tmp/ccvVFJsG.s:12029: Error: operand 1 should be an integer register -- `ldr r1,[sp,8]'
/tmp/ccvVFJsG.s:12030: Error: operand 1 should be an integer register -- `ldr r2,[sp,40]'
/tmp/ccvVFJsG.s:12031: Error: operand 1 should be an integer register -- `ldr r3,[sp,4]'
/tmp/ccvVFJsG.s:12032: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12033: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12034: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12035: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12036: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12037: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12038: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12039: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12040: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12041: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12042: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12043: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12044: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12045: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12046: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12047: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12048: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12049: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12050: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12051: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12052: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12053: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12054: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12055: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12056: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12057: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12058: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12059: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12060: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12061: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12062: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12063: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12064: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12065: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12066: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12067: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12068: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12069: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12070: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12071: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12072: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12073: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12074: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12075: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12076: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12077: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12078: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12079: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12080: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12081: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12082: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12083: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12084: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12085: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12086: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12087: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12088: Error: operand 1 should be an integer register -- `str r2,[sp,40]'
/tmp/ccvVFJsG.s:12089: Error: operand 1 should be an integer register -- `str r1,[sp,8]'
/tmp/ccvVFJsG.s:12090: Error: operand 1 should be an integer register -- `str r0,[sp,16]'
/tmp/ccvVFJsG.s:12109: Error: operand 1 should be an integer register -- `ldr r0,[sp,16]'
/tmp/ccvVFJsG.s:12110: Error: operand 1 should be an integer register -- `ldr r1,[sp,8]'
/tmp/ccvVFJsG.s:12111: Error: operand 1 should be an integer register -- `ldr r2,[sp,40]'
/tmp/ccvVFJsG.s:12112: Error: operand 1 should be an integer register -- `ldr r3,[sp,4]'
/tmp/ccvVFJsG.s:12113: Error: operand 1 should be an integer register -- `ldr r4,[r0],#4'
/tmp/ccvVFJsG.s:12114: Error: operand 1 should be an integer register -- `mov r5,#0'
/tmp/ccvVFJsG.s:12115: Error: operand 1 should be an integer register -- `ldr r6,[r1]'
/tmp/ccvVFJsG.s:12116: Error: operand 1 should be a SIMD vector register -- `umlal r2,r5,r3,r4'
/tmp/ccvVFJsG.s:12117: Error: operand 1 should be an integer register -- `adds r7,r6,r2'
/tmp/ccvVFJsG.s:12118: Error: operand 1 should be an integer register -- `adc r2,r5,#0'
/tmp/ccvVFJsG.s:12119: Error: operand 1 should be an integer register -- `str r7,[r1],#4'
/tmp/ccvVFJsG.s:12120: Error: operand 1 should be an integer register -- `str r2,[sp,40]'
/tmp/ccvVFJsG.s:12121: Error: operand 1 should be an integer register -- `str r1,[sp,8]'
/tmp/ccvVFJsG.s:12122: Error: operand 1 should be an integer register -- `str r0,[sp,16]'
projects/goahead-linux-default.mk:373: recipe for target 'build/linux-arm-default/obj/mbedtls.o' failed
make[1]: *** [build/linux-arm-default/obj/mbedtls.o] Error 1
Makefile:45: recipe for target 'all' failed
make: *** [all] Error 2

build error log above.

my question is how i can fix this compile problem? thanks.

**Comment by mobrien** [comment]
You will need to set the CFLAGS for Arm as well. Typical arm flags include:

* -mno-sched-prolog
* -fomit-frame-pointer
