### ISSUE TITLE
Web documentation is not synchronised with code documentation for usage.

### ISSUE THREAD

**Issue by AdamVStephen** [embedthis/goahead#253]
### Environment

1. O/S Version: Scientific Linux 6.3 linux-x86  

2. GoAhead Version: 3.6.5

3. Hardware: Quad-Core AMD Opteron Processor, 16GB RAM

### Build

1. Checked out commit 82741f9 today
```
git clone http://github.com/embedthis/goahead
cd goahead
make
```
### Problem Description:

Documentation on web page https://embedthis.com/goahead/doc/start/running.html lists the usage as 
goahead [options] [IP]:[PORT] [documents]  

Documentation from the command line usage method states instead (goahead.c)
goahead [options] [documents] [[IPaddress][:port]...]

The source is correct, the web version needs to be revised.

````
# Demonstrate that the order documented does not work
cd build/linux-x86-default-bin
./goahead --home ../../../src :8084 ./
gohead: 0: Unable to open socket on port 80
# Invert the last two arguments
./goahead --home ../../../src ./ :8084 
# Server starts
````

**Comment by mobrien** [comment]
Thanks - fixed. 

We'll push that soon.

Michael

**Comment by mobrien** [comment]
Will be in GoAhead 4.0.0.
