### ISSUE TITLE
upload data patch

### ISSUE THREAD

**Issue by anyhit** [embedthis/goahead#257]
Some upload data (such as tcp data size == 1026 ) will lead the code to ：
```
processContentBoundary
websError(wp, HTTP_CODE_BAD_REQUEST, "Bad upload state. Incomplete boundary");
```

patch:
```
--- upload_old.c        2017-09-30 16:09:54.000000000 +0800
+++ upload.c    2017-09-30 15:58:23.000000000 +0800
@@ -122,10 +122,10 @@
             }   
             *nextTok++ = '\0';
             nbytes = nextTok - line;
-            websConsumeInput(wp, nbytes);
+            // websConsumeInput(wp, nbytes);
             strim(line, "\r", WEBS_TRIM_END);
             len = strlen(line);
-            if (line[len - 1] == '\r') {
+            if (len > 0 && line[len - 1] == '\r') {
                 line[len - 1] = '\0';
             }   
         }   
@@ -136,10 +136,12 @@
 
         case UPLOAD_BOUNDARY:
             processContentBoundary(wp, line);
+            websConsumeInput(wp, nbytes);
             break;
 
         case UPLOAD_CONTENT_HEADER:
             processUploadHeader(wp, line);
+            websConsumeInput(wp, nbytes);
             break;

         case UPLOAD_CONTENT_DATA:
@@ -347,6 +349,7 @@
             /* Get more data */
             return 0;
         }
+       return 0;
     }
     data = content->servp;
     nbytes = (bp) ? (bp - data) : bufLen(content);
```

**Comment by anyhit** [comment]
**websConsumeInput patch**

If ` wp->input.buf` just has one '\r\n', Then `  wp->input.servp == wp->input.buf &&  wp->input.endp!=wp->input.endbuf`

```
   websConsumeInput            =
    bufReset                            
    bp->servp = bp->endp = bp->buf;*bp->servp = '\0'
```
So `strlen(line)==0`
         
 **return patch**
If `(bp = getBoundary(wp, content->servp, size)) == 0 && wp->clientFilename == NULL ` then
```
websConsumeInput
bufAdjustStart
bp->servp += size;
```
The bp->servp error,it shoud  stay the same up to the next socket recv success.

**Comment by mobrien** [comment]
Thank you for the patch.

Can you please do 2 things:

* Post a more complete description of how to provoke the issue. You say TCP data size 1026 but it is not clear what this exactly equates to. Can you post a netcat request that provokes the issue?

* Could you please post full single patch that includes the patches above as one. I'm struggling to understand the 2nd patch.

Thanks

**Comment by anyhit** [comment]
[upload.zip](https://github.com/embedthis/goahead/files/1370724/upload.zip)
1. Attach file is  source code (goahead-3.6.3/src/upload.c)
2. I will provide the bug reproduction step later

Thanks

**Comment by mobrien** [comment]
nbytes may be zero if you come in the websProcessUploadData with state == UPLOAD_BOUNDARY. This can happen.

**Comment by mobrien** [comment]
I'd like to rewind a bit and better understand the problem.

Can you please post a more complete description of how to provoke the issue. You say TCP data size 1026 but it is not clear what this exactly equates to. Can you post a netcat request that provokes the issue?

**Comment by mobrien** [comment]
We cannot reproduce this and have tested all upload sizes from 0 to 10K.
