### ISSUE TITLE
How PUBLIC char *websValidateUriPath(char *uri)` invalidates urls like http://host/AUX

### ISSUE THREAD

**Issue by Acu43** [embedthis/goahead#259]
Hi,

I have a question.

I'm trying to understand how `PUBLIC char *websValidateUriPath(char *uri)` function works.

In goahead version 2.5 it was called `int websValidateUrl(webs_t wp, char_t *path)`

I don't see how the new function invalidates ill formed urls like below. 
http://host/AUX
http://[victim]/cgi_bin/CON

In go-ahead version 2.5 they were hard coded into isWindowsBadPath() function like below
          ```
```
             (badPath(parts[i], T("con"), 3)) ||
             (badPath(parts[i], T("com"), 3)) ||
             (badPath(parts[i], T("nul"), 3)) ||
             (badPath(parts[i], T("aux"), 3)) ||
             (badPath(parts[i], T("clock$"), 6)) ||
             (badPath(parts[i], T("config$"), 7)) ) 

```
  It does not protect against some bad requests. Its stated in this documentation page 10.http://www.codelooker.com/dfilea/301132791NDVS/Webs25ReleaseNotes.pdf

Also whitelisting is shown as a fix. But i can't understand the fix or which code replaced the functionality of isWindowsBadPath().

This is the fix in documentation.
Whitelist-based URL validation eliminates platform-specific interpretation of URLs. URLs of this type are now rejected.

Where are they rejected in the code?

İ have not tested it i'm just triying to understand by reading. Thx. 

Ahmet

**Comment by Acu43** [comment]
Also threre is protective function called isBadWindowsBath() in go ahead 2.5. My question is that which code gives the same protection go ahead 2.5 > versions.

**Comment by mobrien** [comment]
That code was there for windows 95/98/ME which are no longer supported. It was removed to cleanup old legacy code for these O/S versions.
