### ISSUE TITLE
Issues around hashFirst()

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#260]
hashFirst is a public API method that is needed for handling file uploads.
Thus it should be somewhat "hard" and not rely on assumptions about its parameter, i.e., hashFirst should not assert when presented with a sd<0 or a sd >= symMax, instead it should return 0.

Most places inside goAhead test this assumption before calling hashFirst, but

- cgiHandler simply jumps into hashFirst without testing the sd before, thus hashFirst or its caller might crash
- route.c::websCan tests abilities to be >= 0, but asserts in case abilities==0, which is probably a bug of its own, but demonstrates, that hashFirst should not require the user to have internal knowledge about the validity of hash values.

**Comment by mobrien** [comment]
Agree. 

hashFirst should test the sd argument and return NULL if it is out of range. The assertion can / should remain to alert if callers are calling incorrectly, but the product should be robust if asserts are compiled out in production.

Agree on removing the assert in route.c and adding a safety test in cgiHandler.

Thanks for catching these "paper-cut" issues. While not large in themselves, they add up -- so we really want to clean them up. Thank you.
