### ISSUE TITLE
Build Failed In Visual Studio 2017

### ISSUE THREAD

**Issue by eleree** [embedthis/goahead#261]
the path is declared as const pointer,but modify the value in the code.
cchar *path
Start line105:
    if (path[len] == '/') {
        path[len] = '\0';
    } else if (path[len] == '\\') {
        path[len] = '\0';
    }

**Comment by mobrien** [comment]
What file?

**Comment by mobrien** [comment]
This is the result of switching to use const char in the latest update.
Here is a quick fix:

```
#if ME_WIN_LIKE
{
    ssize       len = slen(path) - 1;
    cchar       *p = sclone(path);
    if (p[len] == '/') {
        p[len] = '\0';
    } else if (p[len] == '\\') {
        p[len] = '\0';
    }
    rc = stat(p, &s);
    wfree(p);
}
#else
```

**Comment by eleree** [comment]
@mobrien Thanks!
