### ISSUE TITLE
File upload boundary conditions

### ISSUE THREAD

**Issue by mobrien** [embedthis/goahead#266]
Some file uploads were incorrectly handling file boundary conditions causing file uploads of specific sizes to fail.

**Comment by kkey747** [comment]
not complete fix，because of the TCP recv 1024 bytes once，when a boundary splited in two 1024 bytes，the error occur.

**Comment by dev-embedthis** [comment]
Can you please provide a test case which we can run to reproduce the issue. A more complete description of the issue would be helpful. Thanks.

**Comment by kkey747** [comment]
I upload file "rfc1889.txt", you can get it from https://tools.ietf.org/rfc/rfc1889.txt, test by firefox 59.0.2，it always generate 40+ bytes bondary，when boundary is 44 bytes，must fail，that is easy to test, try few times you can see it
发自我的iPhone

------------------ Original ------------------

**Comment by dev-embedthis** [comment]
Can you please describe the sequence of steps. What upload file/function did you use in GoAhead. Was it the test/upload?

We need a step, by step procedure to reproduce. Otherwise we are guessing and can easily waste a lot of time. Thanks.

**Comment by kkey747** [comment]
1.bootstrap fileinput plugins
2.goahead define action as same as upload example
screenshot of wireshark dump the HTTP POST request:

发自我的iPhone

------------------ Original ------------------

**Comment by dev-embedthis** [comment]
What is

1. boostrap fileinput plugins?

What goahead action

Can you please provide a complete sample. That means the actual goahead action routine and web page / form. We need a complete sample to reproduce.

**Comment by kkey747** [comment]
Sorry, please wait a few days


发自我的iPhone

------------------ Original ------------------

**Comment by kkey747** [comment]
1.patch goahead.c.patch for goahead-4.1.1 goahead.c, that defines post action for test. put css js upload.html to server www directory.

2. run goaehad server

3. open firefox, upload file "test-upload-file.txt" for testing upload.html
4. try several times, you`ll get a bad request from server.



------------------ 原始邮件 ------------------
发件人: "Embedthis Development"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 上午10:06
收件人: "embedthis/goahead"<goahead@noreply.github.com>;
抄送: "47110787"<47110787@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [embedthis/goahead] File upload boundary conditions (#266)




What is
  
boostrap fileinput plugins?
  
What goahead action
 
Can you please provide a complete sample. That means the actual goahead action routine and web page / form. We need a complete sample to reproduce.
