### ISSUE TITLE
When set multi cookies, only the first cookie take effect.

### ISSUE THREAD

**Issue by hhucqian** [embedthis/goahead#275]
When set multi cookies, only the first cookie take effect.

```c
websSetCookie(wp, "nn", "vv", NULL, NULL, 0, WEBS_COOKIE_HTTP);
websSetCookie(wp, "nn2", "vv2", NULL, NULL, 0, WEBS_COOKIE_HTTP);
```
There is a temporary solution:

Change this line 

https://github.com/embedthis/goahead/blob/105fd4f58f1a81a6611dcb27ab42f2e73bf62ef2/src/http.c#L2935

to 

```c
    if (wp->responseCookie) {
        old = wp->responseCookie;
        wp->responseCookie = sfmt("%s \r\nSet-Cookie: %s", wp->responseCookie, cookie);
        wfree(old);
        wfree(cookie);
    } else {
        wp->responseCookie = cookie;
    }
```

But it's not beautiful.

**Comment by dev-embedthis** [comment]
We're converting responseCookie to responseCookies as a list in the next release.
