### ISSUE TITLE
how could goahead work with cJSON?

### ISSUE THREAD

**Issue by dada0z** [embedthis/goahead#284]
This is not an issue.
I want to use cJSON with goahead.
Would somebody give me some suggestions?

**Comment by mobsense** [comment]
Can you be more specific?

**Comment by dada0z** [comment]
I wonder how to output json data in my own action handler easily.
The first library that came to my mind  is cJSON.
Would you please integrate it into goahead as util?

**Comment by dev-embedthis** [comment]
You can just generate using websWrite and generate the JSON directly.

If you have a library like cJSON, then convert the JSON to a string and use websWriteBlock.
