### ISSUE TITLE
How to get data and display in html webpage with out using any submit button in the form?

### ISSUE THREAD

**Issue by kumarfirmware** [embedthis/goahead#292]
Hi Team,

How to get data and display in html webpage with out using any submit button in the form?

I am able to do this using POST method in a form and a submit button.

But if I need to get data and display in webpage with out using any submit button how should I do it?

Please let me know this immediately.

Thanks, Regards
Kumar

**Comment by dev-embedthis** [comment]
If you use

<% code %>

Where Code is any C code you want. 

See the tour which explains pretty well:

https://www.embedthis.com/esp/doc/start/tour.html

**Comment by kumarfirmware** [comment]
Hi Team,

Thanks for your immediate reply. But I am not working on ESP.

I am working on a linux device. This does not work for me .

I am using goahed 5.1 version.

As you suggested I used the following it does not work for me.

<html><head><title>index.html</title></head>
<body>HelloHELLO2 /admin/index.html</body>

<body>Generated on <%Testdate(0)%></body>     

<p>Link to reload <a href="index.html">this page</a></p>
<p>Link to <a href="/action/logout">log out</a></p>

</html>

Testdate() is a C funciton which will return date for me.

Please help me on this immediately.

Thanks, Regards
Kumar.

**Comment by mobsense** [comment]
Hi,

Read this:

https://www.embedthis.com/goahead/doc/users/js.html <https://www.embedthis.com/goahead/doc/users/js.html>

It is the same as ESP in syntax:

<% code %>

In your code, did you define a  function Testdate(0) ?

You can only put validate C code there.

Look at the samples under test/web/*.jst

Cheers

Michael

**Comment by kumarfirmware** [comment]
Hi Michael,

Thanks for your immediate reply.

I spent lot of effort, but still I could not get this up and running. It is really strange.

Please let me know if I am missing anything here? I am really struggling to get this up and running.

Please find the index.html as follows

<html><head><title>index.html</title></head>
<body>HelloHELLO3 /admin/index.html</body>

<%DateTest(0);%>

<p>Link to reload <a href="index.html">this page</a></p>
<p>Link to <a href="/action/logout">log out</a></p>

</html>

please find the DateTest function as follows

static int DateTest(int eid, Webs* wp, int argc, char** argv)
{
	WebsKey* s;
	char buf[200] = "27-12-2019";

	printf("I am in DateTest method \r\n");

	websSetStatus(wp, 200);
	websWriteHeaders(wp, -1, 0);
	websWriteEndHeaders(wp);
	websWrite(wp, "<html><body><pre>\n");

	websWrite(wp, "date=%s\n", buf);

	websWrite(wp, "</pre></body></html>\n");
	websDone(wp);
}
static int DateTest(int eid, Webs* wp, int argc, char** argv);
websDefineJst("DateTest", DateTest);

Thanks, Regards,
Kumar.

**Comment by Isarhamster** [comment]
Either rename your` index.html` to `index.jst` or make sure, that your` route.txt` file contains an entry for routing your URI, look for the place where you find routing handler definitions in `route.txt`:
`route uri=/ extensions=jst handler=jst`
