### ISSUE TITLE
How do you call a JST function in html web page?

### ISSUE THREAD

**Issue by kumarfirmware** [embedthis/goahead#293]
Hi Team,

How do you call a JST function in html web page? Is it possible?

JST function can only be called in JST web page or it can be called in html web page also? If so what is the syntax. This is so confusing.

can I use this <% function(arguments, ...); %> in html page or it can be only used in JST page? please explain.

can you please give me a sample example? 

Please help me with this immediately.

Thanks, Regards,
Kumar.

**Comment by dev-embedthis** [comment]
Only in a JST page which is simply a HTML page with jst extension with embedded <% code %>
