### ISSUE TITLE
Possible null-pointer access in processUploadHeader

### ISSUE THREAD

**Issue by Isarhamster** [embedthis/goahead#295]
In 	upload.c::processUploadHeader()
walloc may fail, thus

```
                file = wp->currentFile = walloc(sizeof(WebsUpload));
                memset(file, 0, sizeof(WebsUpload));
```
should read				
				
```
                file = wp->currentFile = walloc(sizeof(WebsUpload));
                if (file)
                {
                    memset(file, 0, sizeof(WebsUpload));
                    file->clientFilename = sclone(wp->clientFilename);
                    file->filename = sclone(wp->uploadTmp);
                }
		else
                {
                    websError(wp, HTTP_CODE_INTERNAL_SERVER_ERROR,
                              "Cannot allocate file %s.", wp->uploadTmp);
                    return;
                }
```

**Comment by dev-embedthis** [comment]
The memory alloc routines use a global handler (notifier) when any memory allocation fails. The default action is to terminate the process. So we do not check the result of memory allocations in every case, especially for small allocations like this. We rely on the global memory allocator. This is much more reliable than trying to test each and every allocation. The default action in an embedded system for a memory allocation failure is to terminate the process.

So while we do add such tests like you propose, they are not required and the notifier will run before the function returns and will probably terminate the process anyway.
