### ISSUE TITLE
cp: target '/etc/goahead/self.*' is not a directory

### ISSUE THREAD

**Issue by dada0z** [embedthis/goahead#313]
### Issue Submission Template

Please follow this template when submitting each and every issue. Issues without these details will be marked as "Incomplete" and will not get attention. Make sure you use:

* Use markdown to format. Format code with three back ticks. Look at the source of this issue to see how it is done. 

* Edit down any logs. Please do not t just dump large unedited logs. Only post the relevant portions.

* Use the MakeMe **http** command in preference to a browser to trigger the issue. It is more controllable.

* Wherever possible, create an isolated test case, separate from your application to demonstrate the issue. This helps the team to recreate your issue.

* Include these details on ALL issues.

### Environment

1. O/S Version: 
WSL Ubuntu 20.04
2. GoAhead Version: 
5.1.7
3. Hardware: 
PC
### Build

1. If built from source, what was your configure command line:

```
no options
./configure [options]
```

### Problem Description:

I can not copy bin/self.* to /etc/goahead/self.*
I think the destination may be /etc/goahead/

The screenshot as follows.

![image](https://user-images.githubusercontent.com/6371260/155735388-2c8c8daf-928c-4e95-a4a8-2462195bddfb.png)

**Comment by mobsense** [comment]
Can you please re-run with 

sudo make SHOW=1 install 

and post the results

You should have the certificates self.key and self.crt in the build/*/bin directory.

**Comment by mobsense** [comment]
Fixed in the repo.
