### ISSUE TITLE
Redirect to 127.0.0.1 when listening on all interfaces

### ISSUE THREAD

**Issue by AEberleMW** [embedthis/goahead#317]
### Environment

1. O/S Version: ubuntu 20.04 x86_64

2. GoAhead Version: 5.2.0

3. Hardware: AMD Ryzen 7 5700U 

### Build

Using default `make` without any options.

### Problem Description:

When runnig GoAhead with default options from the `test` folder and listening on all available interfaces e.g.
```shell
cd test/
sudo ../build/linux-x64-default/bin/goahead --auth auth.txt --home . --route route.txt --verbose web/ https://*:443
``` 
then all requests to hostnames or IP addresses of the server machine (e.g. ` https://172.16.21.100`) are redirected to `127.0.0.1`.
#### General
```
Request URL: https://172.16.21.100/
Request Method: GET
Status Code: 302 Redirect
Remote Address: 172.16.21.100:443
Referrer Policy: strict-origin-when-cross-origin
```
#### Response Headers
```
Connection: keep-alive
Content-Length: 215
Date: Wed Jun  8 14:28:25 2022
Location: https://127.0.1.1/index.html
X-Frame-Options: SAMEORIGIN
```
#### Request Headers
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
DNT: 1
Host: 172.16.21.100
sec-ch-ua: "Chromium";v="102", " Not A;Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.72 Safari/537.36
```

This works fine when the client is on the same host as the server but will not work if the client request comes from another machine.

I think the fix for #309 is the cause of this behavior because the request does not have a fully qualified URI. So the following line creates the URI based on the host which is now determined from the `websHostUrl` after the mentioned fix. https://github.com/embedthis/goahead/blob/a48496f1267745ce020f4d0054c6169f10dcc32b/src/http.c#L1701 

Is there any possibility to come back to the "old" behavior? Since we always have machines with multiple interfaces, listening on something different than `https://*:443` won't be a good solution.

**Comment by mobsense** [comment]
You need to call websSetHostUrl to define the canonical server address that is used to identify the server.

You cannot use the Host header value as per issue #309. This is a security vulnerability if you do.

**Comment by AEberleMW** [comment]
Thank you for the fast response @mobsense! 

But what should we do, when GoAhead ist listening on multiple interfaces each in a different network? Then the setting the `websHostUrl` will not work for all interfaces.

**Comment by mobsense** [comment]
BTW: if you have a commercial license with support, you can contact Embedthis directly to get support. We've got a patch we are trialing.

**Comment by AEberleMW** [comment]
We have a commercial license without support. 

We could also test the patch for you if available.

**Comment by AEberleMW** [comment]
@mobsense Is there any commit that references the fix?

**Comment by dev-embedthis** [comment]
Pushed, but not released on GitHub.

https://github.com/embedthis/goahead/commit/0b4fbccf13b7a5a37d5b27bd6c7802c112eb748a

**Comment by AEberleMW** [comment]
> Pushed, but not released on GitHub.
> 
> [0b4fbcc](https://github.com/embedthis/goahead/commit/0b4fbccf13b7a5a37d5b27bd6c7802c112eb748a)

Thanks for the information! :+1:
